### ISSUE TITLE
Verify the organization's domains

### ISSUE THREAD

**Issue by elpiel** [AeroRust/WorkingGroup#11]
Assing @o0Ignition0o as he has currently purchased the domains and he has access to the DNS records.

- [x] areweinspaceyet
- [x] aerorust

See [Github Help](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain) for more details

**Comment by o0Ignition0o** [comment]
There we go !

![image](https://user-images.githubusercontent.com/9465678/72429689-d7966f00-3790-11ea-907d-0c0e176bf724.png)

**Comment by elpiel** [comment]
I can confirm that :tada: 
Good and quick job @o0Ignition0o !

![Screenshot from 2020-01-15 13-19-21](https://user-images.githubusercontent.com/8925621/72429948-bc7c2d00-3799-11ea-9162-a741cba905ff.png)
