### ISSUE TITLE
AeroRust Logo

### ISSUE THREAD

**Issue by o0Ignition0o** [AeroRust/WorkingGroup#12]
Track progress and build a logo for the AeroRust WG.

**Comment by arrowcircle** [comment]
Here is concept 
![rustaero](https://user-images.githubusercontent.com/171336/72558203-4a980680-38b3-11ea-9252-bac7b8c292b0.jpg)

**Comment by elpiel** [comment]
Issue #13 has more votes on the first asset for logo and we did choose it (for now).

A lot of people like the idea of @arrowcircle as well and it can be useful for later use in a related crate or smth, so we will keep this idea in mind. Thanks again for the idea!

Closing this one for now.

### The official logo:
![AR_Logotransparent](https://user-images.githubusercontent.com/8925621/75419294-30cff180-593e-11ea-8980-eb8117b06dcd.png)
