### ISSUE TITLE
AeroRust assets proposal

### ISSUE THREAD

**Issue by elpiel** [AeroRust/WorkingGroup#13]
### Proposal:

I've asked a friend of mine to make some assets regarding logo, Ferris, etc. and he sent me the assets yesterday.
I would like to discuss them and see **how** and **if** we should improve them.

I've received a `.ai` (Adobe Illustrator) file as well, which GitHub, apparently, doesn't allow to be uploaded.

This is a proposal regarding #12.

## Logo

![AR_Logotransparent](https://user-images.githubusercontent.com/8925621/73949086-96622c80-4902-11ea-9f0d-747c2500998f.png)

## Surfing Ferris

![AR_Space_Surftransparent](https://user-images.githubusercontent.com/8925621/73949080-9530ff80-4902-11ea-801a-08962b2cd113.png)

## Surfing Ferris between planets

![AR_Space_journeytransparent](https://user-images.githubusercontent.com/8925621/73949084-95c99600-4902-11ea-842d-8116d8113175.png)

## Ferris with fired rocket engines

![AR_Mascotetransparent](https://user-images.githubusercontent.com/8925621/73949085-96622c80-4902-11ea-8ccd-0d1ef0994029.png)

All assets in a pdf file:

[Aero_Rust_01.pdf](https://github.com/AeroRust/WorkingGroup/files/4165724/Aero_Rust_01.pdf)

**Comment by o0Ignition0o** [comment]
I love the surfing ferris between planets

**Comment by oScape** [comment]
I love the last one :D

**Comment by amadeusine** [comment]
They look good, especially the first two. 😄

**Comment by plauche** [comment]
Wow I love all of those! Four and one are my favorites.

**Comment by elpiel** [comment]
I like the first one as well, it has the umlaut and has the Rust gear. I am not really sure about the colours though. Maybe some other colours might be better for it.

Otherwise, the rest looks great, maybe we can only make "Aerorust" one word on the second with umlaut again (for consistency).

**Comment by Evrey** [comment]
The first and last one work better as logos. Proper logos should be easy to caricaturise and minimise. Just like the first and last ones themselves are caricatures. =)
