### ISSUE TITLE
Conferences 2020

### ISSUE THREAD

**Issue by elpiel** [AeroRust/WorkingGroup#14]
### Proposal:
We want to make a list and find a way to track the conferences we want to **attend** to and how we can **approach** them. Some conferences require you to have a _paper_ and to _pay_ for you to read it at the conference.

I think we can divide them into 2 categories:
* Representative(s)
Have at least 1 representative at the conference as an attendee and introduce our community to other attendee's or speakers, organizers, etc.

* Speaker(s)
Submitting at least 1 CFP (Call for papers) to the conference at any topic that can fit the theme of the conference - a talk introducing AeroRust, a project we are working on like [SPLICE](https://github.com/AeroRust/splice) or maybe even making a workshop, etc.

We also have a list of [Public conference list](https://docs.google.com/spreadsheets/d/1bLE3z8J_YeifLSOWApTSsaUnGw55llegXVe-GS6OWqw/edit?usp=sharing).

### Objectives 2020:

- [x] Oxidize Conf https://oxidizeconf.com/ (July 17-20, 2020) 
  - :x: No accepted CFPs
  - :heavy_check_mark: Attended.
- [x] SmallSat https://smallsat.org (August 1-6, 2020)
   - :heavy_check_mark: Attending. See: https://github.com/AeroRust/WorkingGroup/issues/14#issuecomment-662387780
- [x] Rusty Days https://rusty-days.org (27.07 - 02.08.2020)
   - :heavy_check_mark: Accepted Talk. See: https://github.com/AeroRust/WorkingGroup/issues/14#issuecomment-662387780
- [x] live@manning conferences: Rust
   - :heavy_check_mark: Accepted Talk. See: https://github.com/AeroRust/WorkingGroup/issues/14#issuecomment-678604876

**Comment by pwnorbitals** [comment]
I suggest we put up a poll of members who want to attend, centralizing usernames, emails and geographical area. We can then notify the members when an interesting conference pops up in their area :)

**Comment by elpiel** [comment]
Status of current participations:

## SmallSat 2020 Panel
### Panels: https://www.roccor.com/old_space_new_tricks/

#### :heavy_check_mark:  Old Space - New Tricks: Striking the Right Balance
Monday, Aug 3 from 12 – 1 pm MST (UTC -7)

( _I will be joining this one_ )

#### :question: Proliferated LEO & Its Influence on Antenna Architecture
Tuesday, Aug 4 from 12 – 1 pm MST (UTC -7)

#### :question: Where will Solar Sailing take Small Satellites?
Wednesday, Aug 5 from 10 – 11 am MST (UTC -7)

https://www.roccor.com/old_space_new_tricks/

## Rusty Days Talk (https://rusty-days.org)
#### Title: Drone Control - "Controlling a drone using Rust over WiFi"
Date: **29.07 Wednesday 06:00 PM CEST**
For more info: https://rusty-days.org/agenda/#lachezar

- Video steam: https://www.youtube.com/watch?v=XFhrb-qLX_8?t=1382
- Video of the talk:
[![Drone Control - "Controlling a drone using Rust over WiFi"](https://user-images.githubusercontent.com/8925621/88942079-7482aa80-d292-11ea-9cdb-96ddcf85a408.jpeg)](https://www.youtube.com/watch?v=e2mJq9qm_Io)

**Comment by elpiel** [comment]
## SmallSat 2020 Workshop (from [Valispace](https://www.valispace.com/))
#### :heavy_check_mark: Advanced Workshop: Lean Requirements, Verification and Test-Management for Small Satellites

This workshop is also interesting and I will be joining here as well:

 https://zoom.us/meeting/register/tJEvd--oqzopE923FnKHhf0tX4b4NTYC6skh?is=5f180772b6314d7d0186371f

**Comment by elpiel** [comment]
## live@manning conferences: Rust Talk
#### Title: The ÄroRust Working group
Date: **15.09 Tuesday 12:00 - 5:00 PM EST**
For more info: https://freecontent.manning.com/livemanning-conferences-rust/

Video of the talk: 
[![Screenshot from 2021-01-03 12-12-06](https://user-images.githubusercontent.com/8925621/103476273-f6847b80-4dbc-11eb-8d6b-36803f039436.png)](https://youtu.be/9nINNurVqz8?t=15185)
