### ISSUE TITLE
I'm looking for ideas! NASA Space App Challenge 2020

### ISSUE THREAD

**Issue by elpiel** [AeroRust/WorkingGroup#19]
### Ideas for hackathon: NASA Space App Challenge 2020
I am looking for ideas for this year's hackathon.

- What can we use as resources, APIs, data, ,imagery, etc.?
- What is achievable for 2 days work?
- Maybe something not so big, but impactful, simple and relevant?!

Event: https://2020.spaceappschallenge.org/locations/universal-event/
**Participants FAQ:** https://www.spaceappschallenge.org/resources/participant-faq/

----

### :bulb: Proposed Ideas

- Star constellation map (see https://github.com/AeroRust/WorkingGroup/issues/19#issuecomment-697065095)

----

#### Team size: 6 max

_Includes_ : **Resources** relevant for each challenge, like APIs, databases, imagery, etc.
Example: https://earthdata.nasa.gov/eosdis/science-system-description/eosdis-components/gibs

#### Theme:
> This year's theme is "Take Action," a reminder that you can be a part of the solution to our world's challenges. Browse the categories below to start your hackathon journey!

---

### Motivation: Taking action... :construction:

**Comment by Owez** [comment]
Spit-balling: Generate a star consolation map using imagery collected from satilights, using computer vision to identify stars and randomly assign formations to each.

**Comment by elpiel** [comment]
> Spit-balling: Generate a star consolation map using imagery collected from satilights, using computer vision to identify stars and randomly assign formations to each.

@DarkStar1982 also provided some resources that could help with this:
>There is an algorithm that matches star images to star maps
> It is called "lost in space" algorithm, unsurprisingly
- https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=3655&context=smallsat
- https://www.researchgate.net/publication/254199748_Lost-in-Space_Pyramid_Algorithm_for_Robust_Star_Pattern_Recognition

**Comment by alexandercarlis2-dotcom** [comment]
Latitube: 17.044219
Longitube:96.130056
Accuracy:5[]()
