### ISSUE TITLE
1st AeroRust Meetup (virtual) 📅 Date & Time: 19.08.21 17:00 - 19:00 UTC

### ISSUE THREAD

**Issue by elpiel** [AeroRust/WorkingGroup#22]
# :tada:  :tada: The first ever AeroRust community Meetup :tada:  :tada:

It's time to meet and discuss some exciting projects, ideas and really anything related to (aero)space :rocket: and Rust :crab: 

❗ If you'd like to share, discuss or talk about any (aero)space or Rust topics, project, etc. you can comment on this issue bellow 👇

### Event link to [Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=Mm5sdGhtcTdiNG52amY0a3NzamlkNTFkdDEgdnU4M3RhcTcxMDl1dW1qaG5xOHEwNTdrdGNAZw&tmsrc=vu83taq7109uumjhnq8q057ktc%40group.calendar.google.com)

**Video call link**: https://8x8.vc/aerorust/elpiel 
(features: in browser with webrtc, privacy, encryption)
**Password**: 1AeroRustM

_Backup_ Video call link: https://meet.google.com/eep-kjji-fht
(if for some reason 8x8 is not working well we will switch to Google meet)

- [x] Please, fill in the dates and times available to you: ~https://lettucemeet.com/l/ZlZ7p~

### Topics to discuss: (share your bellow)

1. :small_airplane: **Hello Drone** - series of beginners workshops about Drones (by @elpiel ) - We will share our plans for the workshops like:
  - What implementations they will focus on
  - The _topics_ that they will cover
  - What technologies they use
2. General types of satellite boards and why you might want to use each one (like arduino vs raspi)
3. (possible discussion) **How does KubOS work:** A summary with Q+A (by @MoralCode)

**Comment by pwnorbitals** [comment]
Love the idea !

**Comment by elpiel** [comment]
### (Possible) Topic: 3. How does KubOS work: A summary with Q+A

@MoralCode would like to give us a summary of how KubOS works and we will have a Q&A session where anyone can share their experience or ask questions related to KubOS.

**Comment by elpiel** [comment]
### UPDATE: How does KubOS work: A summary with Q+A (might not be discussed)
Due to unavailability, this point might not be discussed at the meetup, however, @MoralCode provided a Draft document of information about KubOS & the KubOS preservation group. You can check it here:

https://docs.google.com/document/d/1YnFTGinvOlI-gN1DCXEIsPHSwpsmbPxb-kdnMfDxWz4/

**Comment by elpiel** [comment]
Yesterday we had the first meetup 🥳 and we've discussed interesting topics about aerospace space opensource and rustlang

We briefly went over Cortex-R  - arm microcontroller family for real-time & safety-critical applications.

**On the next meetup** we might discuss what's needed to get rustlang embedded support for these microcontrollers.

Thank you to everyone that managed to attend.
Expect more details for the next meetup soon and the projects in the next few months 🗞️
