### ISSUE TITLE
Contact Ferrous Systems

### ISSUE THREAD

**Issue by pwnorbitals** [AeroRust/WorkingGroup#7]
### Proposal:

Contact ferrous-systems (https://ferrous-systems.com/) to let them know we exist.

### Objectives:

- Let them know the working group exist
- Find out if they want to work with us

### Motivation:

Their objective of embedding Rust into critical systems (automobile, aerospace, medical, ...) has a lot of common grounds with the objectives of the working group. It might be good for both parties to split-up the work, optimize manpower and share knowledge

I believe @Dylan-DPC is working on getting in touch with them.

**Comment by jamesmunns** [comment]
Hello! We are aware :). What can we do to help?

**Comment by elpiel** [comment]
Hey @jamesmunns , happy to see you onboard with Ferrous Systems!
We are talking about how we can make Rust safe for work in Aerospace.
I think @Dylan-DPC can tell you more about his thoughts, I haven't looked into it too much.
It might not even be `Sealed Rust` and we are not looking to solve such a hard problem over a day or a year, after all.. But it's good to start looking for solutions.
